"""ARCHIVE — turn an adjudicated cycle into a permanent, reproducible artifact
and (optionally) a git commit. Every PROVEN result embeds its runnable sandbox
code and the real output, so any human can re-run and audit it."""
from __future__ import annotations

import subprocess
from pathlib import Path

from . import config, state
from .cycle import CycleResult

_FOLDER = {
    "PROVEN": config.ESTABLISHED,
    "DISPROVEN": config.DISPROVEN,
    "OPEN": config.OPEN,
    "CONJECTURE": config.CONJECTURES,
}


def _evidence_block(runs: list[dict]) -> str:
    if not runs:
        return "_(no sandbox runs)_\n"
    out = []
    for i, r in enumerate(runs, 1):
        out.append(f"**Sandbox run {i}**\n```python\n{r['code']}\n```\n"
                   f"```\n{r['output']}\n```\n")
    return "\n".join(out)


def render_artifact(res: CycleResult, art_id: str) -> str:
    v = res.verdict
    verdict = v.get("verdict", "OPEN").upper()
    conj = res.conjecture
    cited = ", ".join(str(x) for x in v.get("cites", [])) or "AXIOMS.md"
    method = v.get("method")
    method_md = ""
    if method:
        method_md = (f"\n## Reusable method extracted\n"
                     f"**{method.get('name','lemma')}** — {method.get('statement','')}\n")
    return f"""---
id: {art_id}
verdict: {verdict}
title: {v.get('title', conj.get('claim',''))[:120]}
confidence: {v.get('confidence', 0.0)}
question: {res.question.get('question','')}
timestamp: {state.now_iso()}
cites: [{cited}]
---

# {v.get('title', conj.get('claim',''))[:120]}

**Verdict: `{verdict}`**  ·  confidence {v.get('confidence', 0.0)}

## Question
{res.question.get('question','')}

## Hypothesis (falsifiable)
- **Claim:** {conj.get('claim','')}
- **Domain of validity:** {conj.get('domain_of_validity','')}
- **What would falsify it:** {conj.get('falsifier','')}

## Derivation (THE_SCIENTIST)
{res.derivation.final_text or '_(none)_'}

### Sandbox evidence — derivation
{_evidence_block(res.derivation.runs)}

## Falsification attempt (THE_SKEPTIC)
{res.falsification.final_text or '_(none)_'}

### Sandbox evidence — falsification
{_evidence_block(res.falsification.runs)}

## Judgment (THE_JUDGE)
{v.get('reason','')}
{method_md}
---
*Generated by AutoGenius — a god-chosen scientist whose religion is the scientific method.
Every claim here was run in the sandbox before it was written down.*
"""


def archive_result(res: CycleResult) -> Path:
    """Write the artifact, update index/ledger/methods/queue. Returns file path."""
    verdict = res.verdict.get("verdict", "OPEN").upper()
    if verdict not in _FOLDER:
        verdict = "OPEN"
        res.verdict["verdict"] = "OPEN"
    art_id = state.gen_id("art")
    folder = _FOLDER[verdict]
    title = res.verdict.get("title") or res.conjecture.get("claim", "result")
    fname = f"{art_id}_{state.slug(title)}.md"
    path = folder / fname
    path.write_text(render_artifact(res, art_id), encoding="utf-8")

    # index
    state.add_index_entry({
        "id": art_id, "verdict": verdict,
        "title": title[:120], "confidence": res.verdict.get("confidence", 0.0),
        "question": res.question.get("question", ""),
        "path": str(path.relative_to(config.ARCHIVE)).replace("\\", "/"),
        "timestamp": state.now_iso(),
    })

    # ledger (only proven truth is citable)
    if verdict == "PROVEN":
        state.add_to_ledger({
            "id": art_id, "claim": res.conjecture.get("claim", title),
            "artifact": fname, "added": state.now_iso(),
        })

    # reusable method
    method = res.verdict.get("method")
    if method and verdict in ("PROVEN", "DISPROVEN"):
        mp = config.METHODS / f"{state.slug(method.get('name','lemma'))}.md"
        mp.write_text(
            f"# {method.get('name','lemma')}\n\n{method.get('statement','')}\n\n"
            f"_Established in [{art_id}]({('../' + _FOLDER[verdict].name + '/' + fname)})._\n",
            encoding="utf-8")

    # queue: bump attempts, close if decided, enqueue follow-ups
    q = state.load_queue()
    for item in q:
        if item["id"] == res.question.get("id"):
            item["attempts"] = item.get("attempts", 0) + 1
            if verdict in ("PROVEN", "DISPROVEN"):
                item["status"] = "closed"
            elif item["attempts"] >= config.QUESTION_FAIL_CAP:
                item["status"] = "quarantined"
            break
    followups = res.verdict.get("followups") or []
    if followups:
        q = state.add_questions(q, followups, parent=res.question.get("id"))
    state.save_queue(q)
    return path


# --- git -------------------------------------------------------------------
def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=str(config.REPO_ROOT),
                          capture_output=True, text=True, encoding="utf-8", errors="replace")


def is_git_repo() -> bool:
    return _git("rev-parse", "--is-inside-work-tree").returncode == 0


def commit_and_push(message: str, push: bool = True) -> str:
    """Commit the whole archive state. Safe no-op if nothing changed / no repo."""
    if not is_git_repo():
        return "no git repo (skipped commit)"
    _git("add", "-A")
    staged = _git("diff", "--cached", "--quiet")
    if staged.returncode == 0:
        return "nothing to commit"
    c = _git("commit", "-m", f"{message} [skip ci]")
    if c.returncode != 0:
        return f"commit failed: {c.stderr[:200]}"
    if push:
        p = _git("push")
        if p.returncode != 0:
            # concurrent writer (another cycle / the cloud cron) got there first:
            # rebase our single commit on top of theirs and retry once.
            _git("pull", "--rebase")
            p = _git("push")
            if p.returncode != 0:
                return f"committed locally; push failed: {p.stderr[:200]}"
        return "committed and pushed"
    return "committed locally"
